#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO="saturncity/portfolio"
TARGETS=$(node "$(dirname "$0")/deploy-targets.mjs")

banner "Go live on Cloudflare Pages"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Check your tooling"
say "Nothing is changed in this stage. We're just confirming you're logged in"
say "and working out your Cloudflare account id so you never have to type it."
if ! gh auth status >/dev/null 2>&1; then
  warn "gh isn't authenticated. Run 'gh auth login' in another terminal, then re-run this."
  exit 1
fi
step "GitHub CLI is authenticated."
if ! bunx wrangler whoami >/dev/null 2>&1; then
  warn "wrangler isn't logged in. Run 'bunx wrangler login', then re-run this."
  exit 1
fi
CLOUDFLARE_ACCOUNT_ID=$(bunx wrangler whoami 2>/dev/null | grep -oE '[0-9a-f]{32}' | head -1)
if [[ -z "$CLOUDFLARE_ACCOUNT_ID" ]]; then
  warn "Couldn't read your account id from wrangler."
  ask CLOUDFLARE_ACCOUNT_ID "Paste your Cloudflare account id:"
fi
step "Cloudflare account id: $CLOUDFLARE_ACCOUNT_ID"
say ""
say "These sites will be configured:"
while read -r _key project host; do step "$host  ->  $project"; done <<< "$TARGETS"
pause "Look right?"

# ── 2. Create the API token ───────────────────────────────────────────────
stage "Create a Cloudflare API token"
say "CI needs its own token. Your wrangler login won't do, since GitHub can't"
say "use it. This is the only thing in this wizard you have to type."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click 'Create Token', then 'Get started' next to Custom token."
step "Name it something like: github-actions-pages"
step "Under Permissions add:   Account  ·  Cloudflare Pages  ·  Edit"
step "Add a second permission: Zone     ·  DNS              ·  Edit"
say  "  (the DNS one lets the next stage attach your custom domains for you)"
step "Under Account Resources choose: Include · your account"
step "Under Zone Resources choose:    Include · All zones"
step "Click Continue to summary, then Create Token, then copy it."
warn "Cloudflare shows the token exactly once."
ask_secret CLOUDFLARE_API_TOKEN "Paste the token:"
if [[ -z "$CLOUDFLARE_API_TOKEN" ]]; then
  warn "No token entered, so nothing can be deployed by CI."
  exit 1
fi

# ── 3. Store the secrets on GitHub ────────────────────────────────────────
stage "Store the secrets on GitHub"
say "These two names are exactly what .github/workflows/deploy.yml reads."
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
say ""
say "The token itself is deliberately not written to disk. A re-run will ask again."
pause "Continue"

# ── 4. Attach the custom domains ──────────────────────────────────────────
stage "Attach the custom domains"
say "Trying the Cloudflare API for each site. Anything it can't do is listed"
say "at the end as a manual step, so you'll know exactly what's left."
BOUND=0
while read -r _key project host; do
  code=$(curl -s -o /tmp/cf-domain.json -w '%{http_code}' -X POST \
    "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${project}/domains" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "{\"name\":\"${host}\"}" || echo 000)
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$host"
    BOUND=$((BOUND + 1))
  elif grep -q 'already exists\|8000073' /tmp/cf-domain.json 2>/dev/null; then
    printf '  %s✓%s %s (already attached)\n' "$GREEN" "$RESET" "$host"
    BOUND=$((BOUND + 1))
  else
    printf '  %s✗%s %s (HTTP %s)\n' "$YELLOW" "$RESET" "$host" "$code"
    SKIPPED+=("attach $host: Pages project $project, Custom domains, Set up a custom domain")
  fi
done <<< "$TARGETS"
rm -f /tmp/cf-domain.json
say ""
say "Attached $BOUND of 8."
pause "Continue"

# ── 5. Redirect lenzj.com ─────────────────────────────────────────────────
stage "Redirect lenzj.com to lenzj.me"
say "A redirect rule, so no site has to be deployed for lenzj.com to work."
open_url "https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}"
step "Open the lenzj.com zone, then Rules, then Redirect Rules."
step "Create rule, name it: com to me"
step "Match:   Hostname  equals  lenzj.com"
step "Then:    Dynamic redirect"
step "URL expression:  concat(\"https://lenzj.me\", http.request.uri.path)"
step "Status 301, and tick Preserve query string."
step "Deploy the rule."
if confirm "Did the rule save?"; then
  step "Good."
else
  SKIPPED+=("redirect lenzj.com to lenzj.me: Cloudflare, lenzj.com zone, Rules, Redirect Rules")
fi

# ── 6. Prove the pipeline ─────────────────────────────────────────────────
stage "Let CI deploy"
say "Everything so far was setup. This runs the real pipeline end to end so"
say "you know GitHub can deploy without you."
if confirm "Trigger the deploy workflow now?"; then
  gh workflow run deploy.yml --repo "$REPO" >/dev/null 2>&1 || true
  say "Started. Waiting for it to finish..."
  sleep 15
  for _ in $(seq 1 40); do
    status=$(gh run list --repo "$REPO" --limit 1 --json status,conclusion \
      --jq '.[0].status + " " + (.[0].conclusion // "-")' 2>/dev/null || echo "unknown -")
    [[ "${status%% *}" == "completed" ]] && break
    sleep 10
  done
  if [[ "$status" == "completed success" ]]; then
    printf '  %s✓%s CI deployed every site from one commit.\n' "$GREEN" "$RESET"
  else
    warn "Workflow ended as: $status"
    SKIPPED+=("check the run: gh run view --repo $REPO --log-failed")
  fi
else
  SKIPPED+=("deploy: push to main, or run 'gh workflow run deploy.yml'")
fi

finish
